services:
  user:
    build: 
      context: ./backend
      dockerfile: services/user/Dockerfile
    ports:
      - "4001:4001"
      - "9231:9231"
    volumes:
      - ./backend/db:/app/db
    restart: always
    networks:
      - app-network

  game:
    build:
      context: ./backend
      dockerfile: services/game/Dockerfile
    ports:
      - "4002:4002"
      - "9232:9232"
    volumes:
      - ./backend/db:/app/db
    restart: always
    networks:
      - app-network

  matchmaking:
    build:
      context: ./backend
      dockerfile: services/matchmaking/Dockerfile
    ports:
    - "4003:4003"
    - "9229:9229"
    restart: always
    networks:
    - app-network

  gateway:
    build:
      context: ./backend
      dockerfile: gateway/Dockerfile
    ports:
      - "4000:4000"
      - "9230:9230"
    depends_on:
      - user
      - game
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
