services:
  fastify-image:
    container_name: fastify-image
    image: fastify-image
    networks:
      - transcendence
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./pong-fastify:/app
      - ./vite_pong/dist:/app/vite_pong/dist
    working_dir: /app
    command: ["npm", "run", "dev"]

  caddy-image:
    container_name: caddy-image
    networks:
      - transcendence
    image: caddy:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./vite_pong/dist:/usr/share/caddy

networks:
  transcendence:
    name: transcendence
    driver: bridge
