services:
  user:
    build: 
      context: ./backend
      dockerfile: services/user/Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - ./db:/app/db
    restart: always
    networks:
      - app-network

  game:
    build:
      context: ./backend
      dockerfile: services/game/Dockerfile
    ports:
      - "4002:4002"
    volumes:
      - ./db:/app/db
    restart: always
    networks:
      - app-network

  gateway:
    build:
      context: ./backend
      dockerfile: gateway/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - user
      - game
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
