services:
  user:
    build: 
      context: ./backend
      dockerfile: services/user/Dockerfile
    ports:
      - "${USER_SERVICE_PORT}:4001"
      - "9231:9231"
    volumes:
      - ./backend/db:/app/db
    restart: always
    networks:
      - app-network
    env_file: .env

  game:
    build:
      context: ./backend
      dockerfile: services/game/Dockerfile
    ports:
      - "${GAME_SERVICE_PORT}:4002"
      - "9232:9232"
    volumes:
      - ./backend/db:/app/db
    restart: always
    networks:
      - app-network
    env_file: .env

  matchmaking:
    build:
      context: ./backend
      dockerfile: services/matchmaking/Dockerfile
    ports:
    - "${MATCHMAKING_SERVICE_PORT}:4003"
    - "9229:9229"
    restart: always
    networks:
    - app-network
    env_file: .env

  gateway:
    build:
      context: ./backend
      dockerfile: gateway/Dockerfile
    ports:
      - "${GATEWAY_SERVICE_PORT}:4000"
      - "9230:9230"
    depends_on:
      - user
      - game
      - matchmaking
    restart: always
    networks:
      - app-network
    env_file: .env

networks:
  app-network:
    driver: bridge
