
############################ USER ############################
### Inscription
POST http://localhost:4001/user/register
Content-Type: application/json

{
	"userName": "yohan",
	"email": "yo@example.com",
	"password": "123456"
}

### Connexion
POST http://localhost:4001/user/login
Content-Type: application/json

{
	"email": "yo@example.com",
	"password": "123456"
}

### Accéder au profil (JWT requis)
GET http://localhost:4001/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MTI3MDQyMH0.-BOy3HcAD8BDZNjWtmzYeZDKgO3d9Q5UtMVWQ_zznDQ

### 🔍 Voir tous les utilisateurs
GET http://localhost:4001/user/users



############################ GAME ############################

### Start game
POST http://localhost:4002/game/start
Content-Type: application/json

{
	"player1_id": 1,
	"player2_id": 2
}


### Get game
GET http://localhost:4002/game/1


### Update Score
PUT http://localhost:4002/game/1/score
Content-Type: application/json

{"score1": 2, "score2": 3}

### End Game
POST http://localhost:4002/game/1/end
