
############################ USER ############################
### Inscription
POST http://localhost:4001/user/register
Content-Type: application/json

{
	"userName": "test",
	"email": "test@email.com",
	"password": "mypassword"
}

### Connexion
POST http://localhost:4001/user/login
Content-Type: application/json

{
	"email": "test@email.com",
	"password": "mypassword"
}

### Accéder au profil (JWT requis)
GET http://localhost:4001/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTc0MTY5Nzk3OCwiZXhwIjoxNzQxNzg0Mzc4fQ.Q4m9z2-daQXII2kQCG5D_YzkPfZ2p2QdS0GTkUpl8Hw

### 🔍 Voir un utilisateur
GET http://localhost:4001/user/1dfebe57-69a5-4d43-9caf-911f21ebcbb4

### Update info user
PUT http://localhost:4001/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MTcwMzU4NywiZXhwIjoxNzQxNzg5OTg3fQ.6vCZ8h66yq_X9zRHpBuhVkbEZjpkh9yHvhbGi6pKX7s

{
  "userName": "okan",
  "email": "okan@email.com"
}

### Delete un user
DELETE http://localhost:4001/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNzhiMDI4MC04YjVmLTRhZWYtODM5Ny05YTk5OTkwNDE2ZmQiLCJpYXQiOjE3NDE3MDU5NDQsImV4cCI6MTc0MTc5MjM0NH0.acAaJ7rrfhPgc-79VqlQLBNR3COfQqw2o8PIYePKQ3s

{

}
############################ GAME ############################

### Start game
POST http://localhost:4002/game/start
Content-Type: application/json

{
	"player1_id": 1,
	"player2_id": 2
}


### Get game
GET http://localhost:4002/game/2


### Update Score
PUT http://localhost:4002/game/2/score
Content-Type: application/json

{"score1": 2, "score2": 3}

### End Game
POST http://localhost:4002/game/2/end
