{
 "title": "Pong API",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Taille DB SQLite",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sqlite_db_file_bytes", "legendFormat": "{{service}} DB size" }
   ]
  },
  {
   "title": "Latence SQLite p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(sqlite_query_duration_seconds_bucket[5m])) by (le, instance))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence HTTP p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, instance))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erreurs HTTP (4xx/5xx) par service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_errors_total[1m])) by (instance)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requêtes HTTP / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m])) by (instance)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}