{
 "title": "Pong game stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CCU & ongoing games over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(pong_connected_users{instance=\"matchmaking:4003\"}[5m])\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(pong_games_in_progress[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CCU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pong_connected_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Games in progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pong_games_in_progress", "legendFormat": "__auto" }
   ]
  }
 ]
}