-- CREATE TABLE IF NOT EXISTS users (
-- 	id INTEGER PRIMARY KEY AUTOINCREMENT,
-- 	userName TEXT UNIQUE NOT NULL,
-- 	email TEXT UNIQUE NOT NULL,
-- 	password TEXT,
-- 	google_id TEXT_UNIQUE,
-- 	avatar TEXT,
-- 	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

